export const _id = (index: number) => `e99f09a7-dd88-49d5-b1c8-1daf80c2d7b${index}`;

export const _times = (index: number) =>
  // 'MM/DD/YYYY'
  [
    '11/08/2023',
    '04/09/2024',
    '09/12/2023',
    '01/01/2024',
    '04/23/2024',
    '02/29/2024',
    '05/14/2024',
    '01/13/2024',
    '06/22/2024',
    '10/05/2023',
    '07/11/2024',
    '05/22/2024',
    '03/29/2024',
    '08/29/2023',
    '11/19/2023',
    '10/24/2023',
    '12/02/2023',
    '02/13/2024',
    '09/19/2023',
    '04/17/2024',
    '12/18/2023',
    '06/27/2024',
    '10/19/2023',
    '08/09/2024',
  ][index];

export const _fullName = (index: number) =>
  [ "Arjun Sharma",
    "Esha Mehta",
    "Tara Iyer",
    "Sahil Malhotra",
    "Dr. Anjali Rathore",
    "Karan Gupta",
    "Neha Lakhani",
    "Kriti Mishra",
    "Aman Verma",
    "Ravi Joshi",
    "Lata Singh",
    "Mr. Rajat Kapoor",
    "Charulata Rao",
    "Kiran Kulkarni",
    "Bina Shah",
    "Dr. Tarun Menon",
    "Shreya Das",
    "Aditya Ramesh",
    "Dr. Lakshmi Venkatesh",
    "Chitra Pillai",
    "Aryan Bhatt",
    "Ayaan Trivedi",
    "Rohan Khanna",
    "Vikas Anand"
  ][index];

export const _price = (index: number) =>
  [
    35.17, 57.22, 64.78, 50.79, 9.57, 61.46, 96.73, 63.04, 33.18, 36.3, 54.42, 20.52, 62.82, 19.96,
    25.93, 70.39, 23.11, 67.23, 14.31, 31.5, 26.72, 44.8, 37.87, 75.53,
  ][index];

export const _company = (index: number) =>
  [
    "Mumbai, Maharashtra",
    "Delhi, Delhi NCR",
    "Bangalore, Karnataka",
    "Chennai, Tamil Nadu",
    "Hyderabad, Telangana",
    "Kolkata, West Bengal",
    "Pune, Maharashtra",
    "Ahmedabad, Gujarat",
    "Jaipur, Rajasthan",
    "Lucknow, Uttar Pradesh",
    "Chandigarh, Punjab",
    "Coimbatore, Tamil Nadu",
    "Indore, Madhya Pradesh",
    "Kochi, Kerala",
    "Guwahati, Assam",
    "Bhubaneswar, Odisha",
    "Nagpur, Maharashtra",
    "Visakhapatnam, Andhra Pradesh",
    "Vadodara, Gujarat",
    "Surat, Gujarat",
    "Mysore, Karnataka",
    "Thiruvananthapuram, Kerala",
    "Patna, Bihar",
    "Ranchi, Jharkhand",
    "Dehradun, Uttarakhand"
  ][index];

export const _boolean = (index: number) =>
  [
    true,
    false,
    true,
    false,
    true,
    true,
    true,
    false,
    false,
    true,
    false,
    true,
    true,
    false,
    true,
    false,
    false,
    true,
    false,
    false,
    false,
    true,
    true,
    false,
  ][index];

export const _postTitles = (index: number) =>
  [ "Transfer Case to Alternate Regional Branch",
    "Escalation Workflow for Complex Customer Queries",
    "Standard Operating Procedure for First Call Resolution (FCR)",
    "Handling Outbound Call Campaigns Efficiently",
    "Agent Performance Monitoring and Feedback System",
    "Service Recovery Process for Dissatisfied Customers",
    "Customer Data Validation and Update Protocol",
    "Seamless Onboarding Process for New Agents",
    "Multi-Language Support Escalation Framework",
    "Call Queue Management and Prioritization Blueprint",
    "Technical Support Ticket Creation and Resolution Flow",
    "Customer Retention Process for Subscription Services",
    "Data Security and Compliance Workflow",
    "Shift Handover Protocol for 24/7 Operations",
    "Complaint Registration and Resolution Timeline",
    "Cross-Department Collaboration for Issue Resolution",
    "Upgrading CRM Data Systems with Real-Time Updates",
    "Handling High Call Volume Scenarios",
    "Customer Satisfaction Survey and Feedback Loop",
    "Remote Agent Support and Monitoring Framework",
    "Service Level Agreement (SLA) Compliance Process",
    "Knowledge Base Update and Management Workflow",
    "End-of-Day Reporting and Data Reconciliation",
    "Disaster Recovery Plan for Communication Outages"
    ][index];

export const _description = (index: number) =>
  [
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'The Football Is Good For Training And Recreational Purposes',
    'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
    'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    'New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016',
    'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    'The Football Is Good For Training And Recreational Purposes',
    'The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive',
  ][index];

export const _taskNames = (index: number) =>
  [
    `Prepare Monthly Financial Report`,
    `Design New Marketing Campaign`,
    `Analyze Customer Feedback`,
    `Update Website Content`,
    `Conduct Market Research`,
    `Develop Software Application`,
    `Organize Team Meeting`,
    `Create Social Media Posts`,
    `Review Project Plan`,
    `Implement Security Protocols`,
    `Write Technical Documentation`,
    `Test New Product Features`,
    `Manage Client Inquiries`,
    `Train New Employees`,
    `Coordinate Logistics`,
    `Monitor Network Performance`,
    `Develop Training Materials`,
    `Draft Press Release`,
    `Prepare Budget Proposal`,
    `Evaluate Vendor Proposals`,
    `Perform Data Analysis`,
    `Conduct Quality Assurance`,
    `Plan Event Logistics`,
    `Optimize SEO Strategies`,
  ][index];

export const _productNames = (index: number) =>
  [ "Incorrect billing information provided to the customer",
    "Delayed product shipment or delivery issues",
    "Customer unable to reset account password",
    "Miscommunication regarding promotional offers",
    "Technical issues with product functionality",
    "Customer dissatisfaction with service quality",
    "Unavailability of stock for requested products",
    "Order cancellation requests and related refunds",
    "Escalation of unresolved technical issues",
    "Mismatch in the product description and delivery",
    "Lack of clarity in the warranty or return policy",
    "Poor call quality or network interruptions",
    "Duplicate billing or overcharges on customer accounts",
    "Requests for updates on service tickets",
    "Difficulty in navigating the company’s website or app",
    "Confusion regarding subscription plans or renewals",
    "Payment failures or incorrect charges",
    "Delayed response to customer queries",
    "Product replacement issues or defects",
    "Customer confusion over account activity or transactions",
    "Request for account closure or deactivation",
    "Language barriers during communication",
    "Fraudulent activity on customer accounts",
    "Difficulty in understanding service terms and conditions"
  ][index];
